//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: autoconfigure/autoconfigure.go:12
// Source: autoconfigure/autoconfigure.go:16
// Source: autoconfigure/autoconfigure.go:19
// Source: autoconfigure/autoconfigure.go:24
// Source: autoconfigure/autoconfigure.go:29
// Source: autoconfigure/autoconfigure.go:34
// Source: autoconfigure/autoconfigure.go:39
// Source: autoconfigure/autoconfigure.go:44
// Source: autoconfigure/autoconfigure.go:49
// Source: autoconfigure/autoconfigure.go:54
// Source: autoconfigure/autoconfigure.go:59
// Source: autoconfigure/autoconfigure.go:64
// Source: autoconfigure/autoconfigure.go:69
// Source: autoconfigure/autoconfigure.go:75
// Source: autoconfigure/autoconfigure.go:101
// Source: autoconfigure/autoconfigure.go:107
// Source: autoconfigure/autoconfigure.go:113

package spicegen

import (
	fmt "fmt"

	agenttui "github.com/spice-framework/spice-agent-tui"
	autoconfigure "github.com/spice-framework/spice-agent-tui/autoconfigure"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalShell_feec5b69 performs the direct construction selected for bean "terminalShell".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|12:DefaultShell.
func ConstructTerminalShell_feec5b69(dependency0 agenttui.Session, dependency1 agenttui.Renderer, dependency2 agenttui.Theme, dependency3 []agenttui.KeyBinding, dependency4 agenttui.ViewData, dependency5 agenttui.TerminalIO, dependency6 agenttui.TerminalConfig) (agenttui.Shell, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultShell(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6)
	if err != nil {
		var zero agenttui.Shell
		return zero, nil, fmt.Errorf("construct bean terminalShell (github.com/spice-framework/spice-agent-tui.Shell, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|12:DefaultShell): %w", err)
	}
	return value, nil, nil
}

// ConstructDarkTheme_236d4728 performs the direct construction selected for bean "darkTheme".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|16:DefaultDarkTheme.
func ConstructDarkTheme_236d4728() (agenttui.Theme, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultDarkTheme()
	return value, nil, nil
}

// ConstructQuitKeyBinding_92e9bfd2 performs the direct construction selected for bean "quitKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|18:DefaultQuitBinding.
func ConstructQuitKeyBinding_92e9bfd2() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultQuitBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean quitKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|18:DefaultQuitBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructOsTerminalIO_cebac47c performs the direct construction selected for bean "osTerminalIO".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|19:DefaultOSTerminalIO.
func ConstructOsTerminalIO_cebac47c() (agenttui.TerminalIO, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultOSTerminalIO()
	if err != nil {
		var zero agenttui.TerminalIO
		return zero, nil, fmt.Errorf("construct bean osTerminalIO (github.com/spice-framework/spice-agent-tui.TerminalIO, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|19:DefaultOSTerminalIO): %w", err)
	}
	return value, nil, nil
}

// ConstructCancelKeyBinding_8ceb11df performs the direct construction selected for bean "cancelKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultCancelBinding.
func ConstructCancelKeyBinding_8ceb11df() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCancelBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean cancelKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultCancelBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructFixedRenderer_41e915c2 performs the direct construction selected for bean "fixedRenderer".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultFixedRenderer.
func ConstructFixedRenderer_41e915c2() (agenttui.Renderer, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultFixedRenderer()
	return value, nil, nil
}

// ConstructSubmitKeyBinding_91331519 performs the direct construction selected for bean "submitKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultSubmitBinding.
func ConstructSubmitKeyBinding_91331519() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultSubmitBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean submitKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultSubmitBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructConnectingView_8beb18e4 performs the direct construction selected for bean "connectingView".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultConnectingView.
func ConstructConnectingView_8beb18e4() (agenttui.ViewData, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultConnectingView()
	if err != nil {
		var zero agenttui.ViewData
		return zero, nil, fmt.Errorf("construct bean connectingView (github.com/spice-framework/spice-agent-tui.ViewData, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultConnectingView): %w", err)
	}
	return value, nil, nil
}

// ConstructRespondKeyBinding_f5d76bcf performs the direct construction selected for bean "respondKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultRespondBinding.
func ConstructRespondKeyBinding_f5d76bcf() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultRespondBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean respondKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultRespondBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalConfig_1d85063c performs the direct construction selected for bean "terminalConfig".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultTerminalConfig.
func ConstructTerminalConfig_1d85063c() (agenttui.TerminalConfig, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultTerminalConfig()
	return value, nil, nil
}

// ConstructBackspaceKeyBinding_5a57db96 performs the direct construction selected for bean "backspaceKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultBackspaceBinding.
func ConstructBackspaceKeyBinding_5a57db96() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultBackspaceBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean backspaceKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultBackspaceBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructCursorEndKeyBinding_031b5dcd performs the direct construction selected for bean "cursorEndKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultCursorEndBinding.
func ConstructCursorEndKeyBinding_031b5dcd() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCursorEndBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean cursorEndKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultCursorEndBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructCursorLeftKeyBinding_8081e03a performs the direct construction selected for bean "cursorLeftKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|24:DefaultCursorLeftBinding.
func ConstructCursorLeftKeyBinding_8081e03a() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCursorLeftBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean cursorLeftKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|24:DefaultCursorLeftBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructCursorRightKeyBinding_4355a325 performs the direct construction selected for bean "cursorRightKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorRightBinding.
func ConstructCursorRightKeyBinding_4355a325() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCursorRightBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean cursorRightKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorRightBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructCursorStartKeyBinding_886de284 performs the direct construction selected for bean "cursorStartKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorStartBinding.
func ConstructCursorStartKeyBinding_886de284() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCursorStartBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean cursorStartKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorStartBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructHistoryNextKeyBinding_e121877a performs the direct construction selected for bean "historyNextKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultHistoryNextBinding.
func ConstructHistoryNextKeyBinding_e121877a() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultHistoryNextBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean historyNextKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultHistoryNextBinding): %w", err)
	}
	return value, nil, nil
}

// ConstructHistoryPreviousKeyBinding_b62f116c performs the direct construction selected for bean "historyPreviousKeyBinding".
// Spice source identity: spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|29:DefaultHistoryPreviousBinding.
func ConstructHistoryPreviousKeyBinding_b62f116c() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultHistoryPreviousBinding()
	if err != nil {
		var zero agenttui.KeyBinding
		return zero, nil, fmt.Errorf("construct bean historyPreviousKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|29:DefaultHistoryPreviousBinding): %w", err)
	}
	return value, nil, nil
}
