//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/acceptance/composition/application.go:14

package spicegen

// ApplicationTargetCompositionProof_e6a2d1c4 identifies the generated target selected by spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|16:CompositionProof.
const ApplicationTargetCompositionProof_e6a2d1c4 = "compositionproof"
