//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/acceptance/composition/application.go:16
// Source: internal/acceptance/composition/application.go:27
// Source: internal/acceptance/composition/application.go:40

package spicegen

import (
	agenttui "github.com/spice-framework/spice-agent-tui"
	composition "github.com/spice-framework/spice-agent-tui/internal/acceptance/composition"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ApplicationTargetCompositionProof_e6a2d1c4 identifies the generated target selected by spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|16:CompositionProof.
const ApplicationTargetCompositionProof_e6a2d1c4 = "compositionproof"

// ConstructAcceptanceSession_0f987d6a performs the direct construction selected for bean "acceptanceSession".
// Spice source identity: spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|10:NewSession.
func ConstructAcceptanceSession_0f987d6a() (agenttui.Session, spicelifecycle.Cleanup, error) {
	value := composition.NewSession()
	return value, nil, nil
}

// ConstructBindingOrder_af68e5e9 performs the direct construction selected for bean "bindingOrder".
// Spice source identity: spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|15:NewBindingOrder.
func ConstructBindingOrder_af68e5e9(dependency0 []agenttui.KeyBinding) (composition.BindingOrder, spicelifecycle.Cleanup, error) {
	value := composition.NewBindingOrder(dependency0)
	return value, nil, nil
}
