//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/acceptance/composition/binding_order_bean.go:9

package spicegen

import (
	agenttui "github.com/spice-framework/spice-agent-tui"
	composition "github.com/spice-framework/spice-agent-tui/internal/acceptance/composition"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructBindingOrder_af68e5e9 performs the direct construction selected for bean "bindingOrder".
// Spice source identity: spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|15:NewBindingOrder.
func ConstructBindingOrder_af68e5e9(dependency0 []agenttui.KeyBinding) (composition.BindingOrder, spicelifecycle.Cleanup, error) {
	value := composition.NewBindingOrder(dependency0)
	return value, nil, nil
}
