//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/acceptance/composition/session_bean.go:10

package spicegen

import (
	agenttui "github.com/spice-framework/spice-agent-tui"
	composition "github.com/spice-framework/spice-agent-tui/internal/acceptance/composition"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructAcceptanceSession_0f987d6a performs the direct construction selected for bean "acceptanceSession".
// Spice source identity: spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|10:NewSession.
func ConstructAcceptanceSession_0f987d6a() (agenttui.Session, spicelifecycle.Cleanup, error) {
	value := composition.NewSession()
	return value, nil, nil
}
