//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	agenttui "github.com/spice-framework/spice-agent-tui"
	composition "github.com/spice-framework/spice-agent-tui/internal/acceptance/composition"
	spiceAutoconfigure "github.com/spice-framework/spice-agent-tui/internal/spicegen/compositionproof/sources/autoconfigure"
	spiceComposition "github.com/spice-framework/spice-agent-tui/internal/spicegen/compositionproof/sources/internal_/acceptance/composition"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

type applicationDependencies struct {
	darkTheme                 agenttui.Theme
	quitKeyBinding            agenttui.KeyBinding
	osTerminalIO              agenttui.TerminalIO
	cancelKeyBinding          agenttui.KeyBinding
	fixedRenderer             agenttui.Renderer
	submitKeyBinding          agenttui.KeyBinding
	connectingView            agenttui.ViewData
	respondKeyBinding         agenttui.KeyBinding
	terminalConfig            agenttui.TerminalConfig
	backspaceKeyBinding       agenttui.KeyBinding
	cursorEndKeyBinding       agenttui.KeyBinding
	cursorLeftKeyBinding      agenttui.KeyBinding
	cursorRightKeyBinding     agenttui.KeyBinding
	cursorStartKeyBinding     agenttui.KeyBinding
	historyNextKeyBinding     agenttui.KeyBinding
	historyPreviousKeyBinding agenttui.KeyBinding
	acceptanceSession         agenttui.Session
	terminalShell             agenttui.Shell
	bindingOrder              composition.BindingOrder
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	darkTheme, darkThemeCleanup, err := func() (agenttui.Theme, spicelifecycle.Cleanup, error) {
		if options.Overrides.DarkTheme.Enabled() {
			return options.Overrides.DarkTheme.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructDarkTheme_236d4728()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean darkTheme (github.com/spice-framework/spice-agent-tui.Theme, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|16:DefaultDarkTheme): %w", err))
	}
	if darkThemeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|16:DefaultDarkTheme", darkThemeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean darkTheme (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|16:DefaultDarkTheme): %w", err))
		}
	}
	_ = darkTheme
	quitKeyBinding, quitKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.QuitKeyBinding.Enabled() {
			return options.Overrides.QuitKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructQuitKeyBinding_92e9bfd2()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean quitKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|18:DefaultQuitBinding): %w", err))
	}
	if quitKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|18:DefaultQuitBinding", quitKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean quitKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|18:DefaultQuitBinding): %w", err))
		}
	}
	_ = quitKeyBinding
	osTerminalIO, osTerminalIOCleanup, err := func() (agenttui.TerminalIO, spicelifecycle.Cleanup, error) {
		if options.Overrides.OsTerminalIO.Enabled() {
			return options.Overrides.OsTerminalIO.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructOsTerminalIO_cebac47c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean osTerminalIO (github.com/spice-framework/spice-agent-tui.TerminalIO, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|19:DefaultOSTerminalIO): %w", err))
	}
	if osTerminalIOCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|19:DefaultOSTerminalIO", osTerminalIOCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean osTerminalIO (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|19:DefaultOSTerminalIO): %w", err))
		}
	}
	_ = osTerminalIO
	cancelKeyBinding, cancelKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.CancelKeyBinding.Enabled() {
			return options.Overrides.CancelKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructCancelKeyBinding_8ceb11df()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cancelKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultCancelBinding): %w", err))
	}
	if cancelKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultCancelBinding", cancelKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cancelKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultCancelBinding): %w", err))
		}
	}
	_ = cancelKeyBinding
	fixedRenderer, fixedRendererCleanup, err := func() (agenttui.Renderer, spicelifecycle.Cleanup, error) {
		if options.Overrides.FixedRenderer.Enabled() {
			return options.Overrides.FixedRenderer.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructFixedRenderer_41e915c2()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean fixedRenderer (github.com/spice-framework/spice-agent-tui.Renderer, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultFixedRenderer): %w", err))
	}
	if fixedRendererCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultFixedRenderer", fixedRendererCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean fixedRenderer (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultFixedRenderer): %w", err))
		}
	}
	_ = fixedRenderer
	submitKeyBinding, submitKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.SubmitKeyBinding.Enabled() {
			return options.Overrides.SubmitKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructSubmitKeyBinding_91331519()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean submitKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultSubmitBinding): %w", err))
	}
	if submitKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultSubmitBinding", submitKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean submitKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|20:DefaultSubmitBinding): %w", err))
		}
	}
	_ = submitKeyBinding
	connectingView, connectingViewCleanup, err := func() (agenttui.ViewData, spicelifecycle.Cleanup, error) {
		if options.Overrides.ConnectingView.Enabled() {
			return options.Overrides.ConnectingView.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructConnectingView_8beb18e4()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean connectingView (github.com/spice-framework/spice-agent-tui.ViewData, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultConnectingView): %w", err))
	}
	if connectingViewCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultConnectingView", connectingViewCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean connectingView (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultConnectingView): %w", err))
		}
	}
	_ = connectingView
	respondKeyBinding, respondKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.RespondKeyBinding.Enabled() {
			return options.Overrides.RespondKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructRespondKeyBinding_f5d76bcf()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean respondKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultRespondBinding): %w", err))
	}
	if respondKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultRespondBinding", respondKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean respondKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultRespondBinding): %w", err))
		}
	}
	_ = respondKeyBinding
	terminalConfig, terminalConfigCleanup, err := func() (agenttui.TerminalConfig, spicelifecycle.Cleanup, error) {
		if options.Overrides.TerminalConfig.Enabled() {
			return options.Overrides.TerminalConfig.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructTerminalConfig_1d85063c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean terminalConfig (github.com/spice-framework/spice-agent-tui.TerminalConfig, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultTerminalConfig): %w", err))
	}
	if terminalConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultTerminalConfig", terminalConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean terminalConfig (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|21:DefaultTerminalConfig): %w", err))
		}
	}
	_ = terminalConfig
	backspaceKeyBinding, backspaceKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.BackspaceKeyBinding.Enabled() {
			return options.Overrides.BackspaceKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructBackspaceKeyBinding_5a57db96()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean backspaceKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultBackspaceBinding): %w", err))
	}
	if backspaceKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultBackspaceBinding", backspaceKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean backspaceKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultBackspaceBinding): %w", err))
		}
	}
	_ = backspaceKeyBinding
	cursorEndKeyBinding, cursorEndKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.CursorEndKeyBinding.Enabled() {
			return options.Overrides.CursorEndKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructCursorEndKeyBinding_031b5dcd()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cursorEndKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultCursorEndBinding): %w", err))
	}
	if cursorEndKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultCursorEndBinding", cursorEndKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cursorEndKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|23:DefaultCursorEndBinding): %w", err))
		}
	}
	_ = cursorEndKeyBinding
	cursorLeftKeyBinding, cursorLeftKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.CursorLeftKeyBinding.Enabled() {
			return options.Overrides.CursorLeftKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructCursorLeftKeyBinding_8081e03a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cursorLeftKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|24:DefaultCursorLeftBinding): %w", err))
	}
	if cursorLeftKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|24:DefaultCursorLeftBinding", cursorLeftKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cursorLeftKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|24:DefaultCursorLeftBinding): %w", err))
		}
	}
	_ = cursorLeftKeyBinding
	cursorRightKeyBinding, cursorRightKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.CursorRightKeyBinding.Enabled() {
			return options.Overrides.CursorRightKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructCursorRightKeyBinding_4355a325()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cursorRightKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorRightBinding): %w", err))
	}
	if cursorRightKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorRightBinding", cursorRightKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cursorRightKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorRightBinding): %w", err))
		}
	}
	_ = cursorRightKeyBinding
	cursorStartKeyBinding, cursorStartKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.CursorStartKeyBinding.Enabled() {
			return options.Overrides.CursorStartKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructCursorStartKeyBinding_886de284()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cursorStartKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorStartBinding): %w", err))
	}
	if cursorStartKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorStartBinding", cursorStartKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cursorStartKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultCursorStartBinding): %w", err))
		}
	}
	_ = cursorStartKeyBinding
	historyNextKeyBinding, historyNextKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.HistoryNextKeyBinding.Enabled() {
			return options.Overrides.HistoryNextKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructHistoryNextKeyBinding_e121877a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean historyNextKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultHistoryNextBinding): %w", err))
	}
	if historyNextKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultHistoryNextBinding", historyNextKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean historyNextKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|25:DefaultHistoryNextBinding): %w", err))
		}
	}
	_ = historyNextKeyBinding
	historyPreviousKeyBinding, historyPreviousKeyBindingCleanup, err := func() (agenttui.KeyBinding, spicelifecycle.Cleanup, error) {
		if options.Overrides.HistoryPreviousKeyBinding.Enabled() {
			return options.Overrides.HistoryPreviousKeyBinding.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructHistoryPreviousKeyBinding_b62f116c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean historyPreviousKeyBinding (github.com/spice-framework/spice-agent-tui.KeyBinding, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|29:DefaultHistoryPreviousBinding): %w", err))
	}
	if historyPreviousKeyBindingCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|29:DefaultHistoryPreviousBinding", historyPreviousKeyBindingCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean historyPreviousKeyBinding (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|29:DefaultHistoryPreviousBinding): %w", err))
		}
	}
	_ = historyPreviousKeyBinding
	acceptanceSession, acceptanceSessionCleanup, err := func() (agenttui.Session, spicelifecycle.Cleanup, error) {
		if options.Overrides.AcceptanceSession.Enabled() {
			return options.Overrides.AcceptanceSession.Acquire(ctx)
		}
		return spiceComposition.ConstructAcceptanceSession_0f987d6a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean acceptanceSession (github.com/spice-framework/spice-agent-tui.Session, source spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|10:NewSession): %w", err))
	}
	if acceptanceSessionCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|10:NewSession", acceptanceSessionCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean acceptanceSession (source spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|10:NewSession): %w", err))
		}
	}
	_ = acceptanceSession
	terminalShell, terminalShellCleanup, err := func() (agenttui.Shell, spicelifecycle.Cleanup, error) {
		if options.Overrides.TerminalShell.Enabled() {
			return options.Overrides.TerminalShell.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructTerminalShell_feec5b69(acceptanceSession, fixedRenderer, darkTheme, []agenttui.KeyBinding{submitKeyBinding, cancelKeyBinding, respondKeyBinding, quitKeyBinding, cursorLeftKeyBinding, cursorRightKeyBinding, cursorStartKeyBinding, cursorEndKeyBinding, historyPreviousKeyBinding, historyNextKeyBinding, backspaceKeyBinding}, connectingView, osTerminalIO, terminalConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean terminalShell (github.com/spice-framework/spice-agent-tui.Shell, source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|12:DefaultShell): %w", err))
	}
	if terminalShellCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|12:DefaultShell", terminalShellCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean terminalShell (source spice:symbol:v1|function|56:github.com/spice-framework/spice-agent-tui/autoconfigure|0:|12:DefaultShell): %w", err))
		}
	}
	_ = terminalShell
	bindingOrder, bindingOrderCleanup, err := func() (composition.BindingOrder, spicelifecycle.Cleanup, error) {
		if options.Overrides.BindingOrder.Enabled() {
			return options.Overrides.BindingOrder.Acquire(ctx)
		}
		return spiceComposition.ConstructBindingOrder_af68e5e9([]agenttui.KeyBinding{submitKeyBinding, cancelKeyBinding, respondKeyBinding, quitKeyBinding, cursorLeftKeyBinding, cursorRightKeyBinding, cursorStartKeyBinding, cursorEndKeyBinding, historyPreviousKeyBinding, historyNextKeyBinding, backspaceKeyBinding})
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean bindingOrder (github.com/spice-framework/spice-agent-tui/internal/acceptance/composition.BindingOrder, source spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|15:NewBindingOrder): %w", err))
	}
	if bindingOrderCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|15:NewBindingOrder", bindingOrderCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean bindingOrder (source spice:symbol:v1|function|74:github.com/spice-framework/spice-agent-tui/internal/acceptance/composition|0:|15:NewBindingOrder): %w", err))
		}
	}
	_ = bindingOrder
	return &applicationDependencies{
		darkTheme:                 darkTheme,
		quitKeyBinding:            quitKeyBinding,
		osTerminalIO:              osTerminalIO,
		cancelKeyBinding:          cancelKeyBinding,
		fixedRenderer:             fixedRenderer,
		submitKeyBinding:          submitKeyBinding,
		connectingView:            connectingView,
		respondKeyBinding:         respondKeyBinding,
		terminalConfig:            terminalConfig,
		backspaceKeyBinding:       backspaceKeyBinding,
		cursorEndKeyBinding:       cursorEndKeyBinding,
		cursorLeftKeyBinding:      cursorLeftKeyBinding,
		cursorRightKeyBinding:     cursorRightKeyBinding,
		cursorStartKeyBinding:     cursorStartKeyBinding,
		historyNextKeyBinding:     historyNextKeyBinding,
		historyPreviousKeyBinding: historyPreviousKeyBinding,
		acceptanceSession:         acceptanceSession,
		terminalShell:             terminalShell,
		bindingOrder:              bindingOrder,
	}, nil
}
