//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application compositionproof: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application compositionproof: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application compositionproof: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application compositionproof: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application compositionproof: duration must be positive"))
	}
	dependencies, err := constructApplicationDependencies(ctx, application, options, configurationSnapshot)
	if err != nil {
		return nil, err
	}
	_ = dependencies
	application.components = Components{
		DarkTheme:                 dependencies.darkTheme,
		QuitKeyBinding:            dependencies.quitKeyBinding,
		OsTerminalIO:              dependencies.osTerminalIO,
		CancelKeyBinding:          dependencies.cancelKeyBinding,
		FixedRenderer:             dependencies.fixedRenderer,
		SubmitKeyBinding:          dependencies.submitKeyBinding,
		ConnectingView:            dependencies.connectingView,
		RespondKeyBinding:         dependencies.respondKeyBinding,
		TerminalConfig:            dependencies.terminalConfig,
		BackspaceKeyBinding:       dependencies.backspaceKeyBinding,
		CursorEndKeyBinding:       dependencies.cursorEndKeyBinding,
		CursorLeftKeyBinding:      dependencies.cursorLeftKeyBinding,
		CursorRightKeyBinding:     dependencies.cursorRightKeyBinding,
		CursorStartKeyBinding:     dependencies.cursorStartKeyBinding,
		HistoryNextKeyBinding:     dependencies.historyNextKeyBinding,
		HistoryPreviousKeyBinding: dependencies.historyPreviousKeyBinding,
		AcceptanceSession:         dependencies.acceptanceSession,
		TerminalShell:             dependencies.terminalShell,
		BindingOrder:              dependencies.bindingOrder,
	}
	return application, nil
}
