package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestStyleArgumentsAreExactAndBounded(t *testing.T) {
	t.Parallel()
	want := []string{"--config=.spice/style.json", "./internal/acceptance/composition"}
	if got := styleArguments(); !slices.Equal(got, want) {
		t.Fatalf("style arguments = %q, want %q", got, want)
	}
}

func TestStyleContractIsExactAndOwnsGeneratedSources(t *testing.T) {
	t.Parallel()
	root := styleContractFixture(t)
	if err := checkStyleContract(root); err != nil {
		t.Fatal(err)
	}

	configuration, err := os.ReadFile(filepath.Join(root, ".spice", "style.json"))
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct {
		name string
		from string
		to   string
		want string
	}{
		{name: "schema one", from: `"schemaVersion": 2`, to: `"schemaVersion": 1`, want: "schemaVersion 2"},
		{name: "source escape", from: `"internal/acceptance/composition"`, to: `"../outside"`, want: "exact reviewed"},
		{name: "generated root drift", from: `"internal/spicegen/compositionproof"`, to: `"internal/generated"`, want: "exact reviewed"},
		{name: "second disabled rule", from: `"explicitManagedScopes": "error"`, to: `"explicitManagedScopes": "off"`, want: "only moduleOwnership"},
		{name: "enabled module ownership", from: `"moduleOwnership": "off"`, to: `"moduleOwnership": "error"`, want: "cannot include the module-root package '.'"},
		{name: "build selection drift", from: `"goos": "windows"`, to: `"goos": "darwin"`, want: "exact reviewed"},
	} {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			mutated := styleContractFixture(t)
			writeFile(t, mutated, ".spice/style.json", strings.Replace(string(configuration), test.from, test.to, 1))
			err := checkStyleContract(mutated)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("checkStyleContract() error = %v, want containing %q", err, test.want)
			}
		})
	}
}

func TestStyleContractRejectsGeneratedMarkerBypassAndOwnershipDrift(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name    string
		path    string
		content string
		want    string
	}{
		{
			name:    "handwritten generated-looking source",
			path:    "internal/acceptance/composition/bypass.go",
			content: "// Code generated by a person. DO NOT EDIT.\npackage composition\n",
			want:    "must not use a generated-file marker",
		},
		{
			name:    "plain source in generated root",
			path:    "internal/spicegen/compositionproof/plain.go",
			content: "package compositionproof\n",
			want:    "missing the standard generated-file marker",
		},
		{
			name:    "generated source outside exact root",
			path:    "internal/spicegen/escape/escape.go",
			content: "// Code generated by Spice. DO NOT EDIT.\npackage escape\n",
			want:    "outside exact root",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			root := styleContractFixture(t)
			writeFile(t, root, test.path, test.content)
			err := checkStyleContract(root)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("checkStyleContract() error = %v, want containing %q", err, test.want)
			}
		})
	}
}

func styleContractFixture(t *testing.T) string {
	t.Helper()
	source, err := repositoryRoot()
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	for _, path := range []string{"CODE_STYLE.md", ".spice/style.json"} {
		content, readErr := os.ReadFile(filepath.Join(source, filepath.FromSlash(path)))
		if readErr != nil {
			t.Fatal(readErr)
		}
		writeFile(t, root, path, string(content))
	}
	writeFile(t, root, "internal/acceptance/composition/doc.go", "package composition\n")
	writeFile(
		t,
		root,
		"internal/spicegen/compositionproof/generated.go",
		"// Code generated by Spice. DO NOT EDIT.\npackage compositionproof\n",
	)
	return root
}
