name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-module-release.yml@07f898b85e7d1c409b91bf280e47d62921e786b6
    with:
      module: github.com/spice-framework/spice-agent-tui
      workflow_commit: 07f898b85e7d1c409b91bf280e47d62921e786b6
