name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-module-release.yml@c4df74b2c60640c60fe0fa3fe641dadafbc4148a
    with:
      module: github.com/spice-framework/spice-agent-tui
      workflow_commit: c4df74b2c60640c60fe0fa3fe641dadafbc4148a
