name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-module-release.yml@0fcd43dc8b41fad56c231d0e136ad8c762276ed5
    with:
      module: github.com/spice-framework/spice-agent-tui
      workflow_commit: 0fcd43dc8b41fad56c231d0e136ad8c762276ed5
